/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface Profile {
  'monthlyBudget' : number,
  'passcode' : [] | [bigint],
  'name' : string,
  'schoolClass' : string,
  'savingsGoal' : number,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'reminderMinutes' : [] | [bigint],
  'subject' : string,
  'recurring' : boolean,
  'completed' : boolean,
  'durationHours' : number,
  'dueDate' : Time,
  'isExam' : boolean,
  'priority' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAITask' : ActorMethod<[string, string, string], undefined>,
  'addExpense' : ActorMethod<[number, string, Time, string], undefined>,
  'addTask' : ActorMethod<
    [string, string, Time, boolean, number, boolean, string, [] | [bigint]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeProfile' : ActorMethod<[string, string, [] | [bigint]], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasks' : ActorMethod<[], Array<Task>>,
  'getExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'getFinancialOverview' : ActorMethod<[], [number, number]>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTaskCompletionBySubject' : ActorMethod<[string], number>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUpcomingExams' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getWeekStudyHours' : ActorMethod<[], Array<number>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logStudySession' : ActorMethod<[string, number, Time], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'setMonthlyBudget' : ActorMethod<[number], undefined>,
  'setSavingsGoal' : ActorMethod<[number], undefined>,
  'updateTask' : ActorMethod<[bigint, Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];