/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Profile = IDL.Record({
  'monthlyBudget' : IDL.Float64,
  'passcode' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'schoolClass' : IDL.Text,
  'savingsGoal' : IDL.Float64,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'reminderMinutes' : IDL.Opt(IDL.Nat),
  'subject' : IDL.Text,
  'recurring' : IDL.Bool,
  'completed' : IDL.Bool,
  'durationHours' : IDL.Float64,
  'dueDate' : Time,
  'isExam' : IDL.Bool,
  'priority' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAITask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addExpense' : IDL.Func([IDL.Float64, IDL.Text, Time, IDL.Text], [], []),
  'addTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Bool,
        IDL.Float64,
        IDL.Bool,
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getExpensesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getFinancialOverview' : IDL.Func([], [IDL.Float64, IDL.Float64], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTaskCompletionBySubject' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUpcomingExams' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getWeekStudyHours' : IDL.Func([], [IDL.Vec(IDL.Float64)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logStudySession' : IDL.Func([IDL.Text, IDL.Float64, Time], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'setMonthlyBudget' : IDL.Func([IDL.Float64], [], []),
  'setSavingsGoal' : IDL.Func([IDL.Float64], [], []),
  'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Profile = IDL.Record({
    'monthlyBudget' : IDL.Float64,
    'passcode' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'schoolClass' : IDL.Text,
    'savingsGoal' : IDL.Float64,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'reminderMinutes' : IDL.Opt(IDL.Nat),
    'subject' : IDL.Text,
    'recurring' : IDL.Bool,
    'completed' : IDL.Bool,
    'durationHours' : IDL.Float64,
    'dueDate' : Time,
    'isExam' : IDL.Bool,
    'priority' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAITask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addExpense' : IDL.Func([IDL.Float64, IDL.Text, Time, IDL.Text], [], []),
    'addTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Bool,
          IDL.Float64,
          IDL.Bool,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getFinancialOverview' : IDL.Func(
        [],
        [IDL.Float64, IDL.Float64],
        ['query'],
      ),
    'getTask' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTaskCompletionBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUpcomingExams' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getWeekStudyHours' : IDL.Func([], [IDL.Vec(IDL.Float64)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logStudySession' : IDL.Func([IDL.Text, IDL.Float64, Time], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'setMonthlyBudget' : IDL.Func([IDL.Float64], [], []),
    'setSavingsGoal' : IDL.Func([IDL.Float64], [], []),
    'updateTask' : IDL.Func([IDL.Nat, Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };